# Generated by Django 4.0.6 on 2022-07-25 13:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0002_rename_user_id_notes_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
    ]
