# Generated by Django 4.0.6 on 2022-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.BigIntegerField(max_length=20)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
