# Generated by Django 4.0.6 on 2022-08-18 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
